# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Docs & Blog
author:
  name: Umut Yalcinkaya
  email: yalcinkayaumut@outlook.com
description: > # this means to ignore newlines until "show_excerpts:"
  Written by Umut Yalçınkaya who lives and works in Amsterdam building purposeful things. 
  You could follow him on Twitter
show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
theme: minima
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: umutykaya
    github:  umutykaya
    linkedin: umutykaya
markdown: kramdown

header_pages:
  - about.md
  - projects.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin

# Admin CMS
# jekyll_admin:
#   hidden_links:
#     - posts
#     - pages
#     - staticfiles
#     - datafiles
#     - configuration
# homepage: "pages"
